# -*- coding: utf-8 -*-
"""Untitled7 (3).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10bvh77iexcI0nfFd78qIe_Kt-R3Q4xAR
"""

from sklearn.datasets import load_iris
from sklearn.cluster import AgglomerativeClustering
import numpy as np
import pandas as pd
import matplotlib as plt
from scipy.cluster.hierarchy import dendrogram, linkage
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
import pickle

df = pd.read_excel('qog_std_ts_jan22.csv')
df.head(120)

df.shape

data = load_iris()
df = data.data
df = df[:,1:3]

Z = linkage(df, method='ward')
dend = dendrogram(Z)
plt.title("Dendrogram")
plt.ylabel("Euclidean distances")
plt.show()

model = AgglomerativeClustering

model.fit_predict

filename = 'finalized_model.sav'
pickle.dump(model, open(filename, 'wb'))